# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Pythons\VIP-Playlist-Downloader\ui\vip.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(789, 626)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.verticalLayout_main = QtGui.QVBoxLayout()
        self.verticalLayout_main.setSpacing(0)
        self.verticalLayout_main.setObjectName(_fromUtf8("verticalLayout_main"))
        self.verticalLayout_media_seekbar = QtGui.QVBoxLayout()
        self.verticalLayout_media_seekbar.setMargin(6)
        self.verticalLayout_media_seekbar.setObjectName(_fromUtf8("verticalLayout_media_seekbar"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_vip_standard = QtGui.QWidget()
        self.tab_vip_standard.setObjectName(_fromUtf8("tab_vip_standard"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tab_vip_standard)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setHorizontalSpacing(6)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.table_vip_standard = QtGui.QTableWidget(self.tab_vip_standard)
        self.table_vip_standard.setLineWidth(1)
        self.table_vip_standard.setObjectName(_fromUtf8("table_vip_standard"))
        self.table_vip_standard.setColumnCount(5)
        self.table_vip_standard.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.table_vip_standard.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.table_vip_standard.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignVCenter)
        self.table_vip_standard.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignVCenter)
        self.table_vip_standard.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.table_vip_standard.setHorizontalHeaderItem(4, item)
        self.gridLayout_2.addWidget(self.table_vip_standard, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_vip_standard, _fromUtf8(""))
        self.tab_vip_mellow = QtGui.QWidget()
        self.tab_vip_mellow.setObjectName(_fromUtf8("tab_vip_mellow"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tab_vip_mellow)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.table_vip_mellow = QtGui.QTableWidget(self.tab_vip_mellow)
        self.table_vip_mellow.setObjectName(_fromUtf8("table_vip_mellow"))
        self.table_vip_mellow.setColumnCount(0)
        self.table_vip_mellow.setRowCount(0)
        self.gridLayout_3.addWidget(self.table_vip_mellow, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_vip_mellow, _fromUtf8(""))
        self.tab_vip_source = QtGui.QWidget()
        self.tab_vip_source.setObjectName(_fromUtf8("tab_vip_source"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tab_vip_source)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.table_vip_source = QtGui.QTableWidget(self.tab_vip_source)
        self.table_vip_source.setObjectName(_fromUtf8("table_vip_source"))
        self.table_vip_source.setColumnCount(0)
        self.table_vip_source.setRowCount(0)
        self.gridLayout_4.addWidget(self.table_vip_source, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_vip_source, _fromUtf8(""))
        self.tab_vip_exiled = QtGui.QWidget()
        self.tab_vip_exiled.setObjectName(_fromUtf8("tab_vip_exiled"))
        self.gridLayout_5 = QtGui.QGridLayout(self.tab_vip_exiled)
        self.gridLayout_5.setMargin(0)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.table_vip_exiled = QtGui.QTableWidget(self.tab_vip_exiled)
        self.table_vip_exiled.setObjectName(_fromUtf8("table_vip_exiled"))
        self.table_vip_exiled.setColumnCount(0)
        self.table_vip_exiled.setRowCount(0)
        self.gridLayout_5.addWidget(self.table_vip_exiled, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_vip_exiled, _fromUtf8(""))
        self.tab_wap_anime = QtGui.QWidget()
        self.tab_wap_anime.setObjectName(_fromUtf8("tab_wap_anime"))
        self.gridLayout_6 = QtGui.QGridLayout(self.tab_wap_anime)
        self.gridLayout_6.setMargin(0)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.table_wap_anime = QtGui.QTableWidget(self.tab_wap_anime)
        self.table_wap_anime.setObjectName(_fromUtf8("table_wap_anime"))
        self.table_wap_anime.setColumnCount(0)
        self.table_wap_anime.setRowCount(0)
        self.gridLayout_6.addWidget(self.table_wap_anime, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_wap_anime, _fromUtf8(""))
        self.verticalLayout_media_seekbar.addWidget(self.tabWidget)
        self.horizontalLayout_seekbar = QtGui.QHBoxLayout()
        self.horizontalLayout_seekbar.setContentsMargins(-1, -1, -1, 2)
        self.horizontalLayout_seekbar.setObjectName(_fromUtf8("horizontalLayout_seekbar"))
        self.seekSlider = phonon.Phonon.SeekSlider(self.centralwidget)
        self.seekSlider.setIconVisible(True)
        self.seekSlider.setObjectName(_fromUtf8("seekSlider"))
        self.horizontalLayout_seekbar.addWidget(self.seekSlider)
        self.lcdNumber_player = QtGui.QLCDNumber(self.centralwidget)
        self.lcdNumber_player.setObjectName(_fromUtf8("lcdNumber_player"))
        self.horizontalLayout_seekbar.addWidget(self.lcdNumber_player)
        self.verticalLayout_media_seekbar.addLayout(self.horizontalLayout_seekbar)
        self.horizontalLayout_media_controls = QtGui.QHBoxLayout()
        self.horizontalLayout_media_controls.setContentsMargins(-1, 2, -1, -1)
        self.horizontalLayout_media_controls.setObjectName(_fromUtf8("horizontalLayout_media_controls"))
        self.horizontalLayout_media_control_buttons = QtGui.QHBoxLayout()
        self.horizontalLayout_media_control_buttons.setObjectName(_fromUtf8("horizontalLayout_media_control_buttons"))
        self.pushButton_media_play = QtGui.QPushButton(self.centralwidget)
        self.pushButton_media_play.setObjectName(_fromUtf8("pushButton_media_play"))
        self.horizontalLayout_media_control_buttons.addWidget(self.pushButton_media_play)
        self.pushButton_media_pause = QtGui.QPushButton(self.centralwidget)
        self.pushButton_media_pause.setObjectName(_fromUtf8("pushButton_media_pause"))
        self.horizontalLayout_media_control_buttons.addWidget(self.pushButton_media_pause)
        self.pushButton_media_stop = QtGui.QPushButton(self.centralwidget)
        self.pushButton_media_stop.setObjectName(_fromUtf8("pushButton_media_stop"))
        self.horizontalLayout_media_control_buttons.addWidget(self.pushButton_media_stop)
        self.horizontalLayout_media_controls.addLayout(self.horizontalLayout_media_control_buttons)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_media_controls.addItem(spacerItem)
        self.volumeSlider = phonon.Phonon.VolumeSlider(self.centralwidget)
        self.volumeSlider.setObjectName(_fromUtf8("volumeSlider"))
        self.horizontalLayout_media_controls.addWidget(self.volumeSlider)
        self.horizontalLayout_media_controls.setStretch(1, 1)
        self.verticalLayout_media_seekbar.addLayout(self.horizontalLayout_media_controls)
        self.verticalLayout_main.addLayout(self.verticalLayout_media_seekbar)
        self.verticalLayout_3.addLayout(self.verticalLayout_main)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 789, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuPlaylist = QtGui.QMenu(self.menubar)
        self.menuPlaylist.setObjectName(_fromUtf8("menuPlaylist"))
        self.menuAbout = QtGui.QMenu(self.menubar)
        self.menuAbout.setObjectName(_fromUtf8("menuAbout"))
        MainWindow.setMenuBar(self.menubar)
        self.playlist_toolBar = QtGui.QToolBar(MainWindow)
        self.playlist_toolBar.setMovable(False)
        self.playlist_toolBar.setFloatable(False)
        self.playlist_toolBar.setObjectName(_fromUtf8("playlist_toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.playlist_toolBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)
        self.actionVIP_Standard = QtGui.QAction(MainWindow)
        self.actionVIP_Standard.setCheckable(True)
        self.actionVIP_Standard.setObjectName(_fromUtf8("actionVIP_Standard"))
        self.actionVIP_Mellow = QtGui.QAction(MainWindow)
        self.actionVIP_Mellow.setCheckable(True)
        self.actionVIP_Mellow.setObjectName(_fromUtf8("actionVIP_Mellow"))
        self.actionVIP_Source = QtGui.QAction(MainWindow)
        self.actionVIP_Source.setCheckable(True)
        self.actionVIP_Source.setObjectName(_fromUtf8("actionVIP_Source"))
        self.actionVIP_Exiled = QtGui.QAction(MainWindow)
        self.actionVIP_Exiled.setCheckable(True)
        self.actionVIP_Exiled.setObjectName(_fromUtf8("actionVIP_Exiled"))
        self.actionWAP_Anime = QtGui.QAction(MainWindow)
        self.actionWAP_Anime.setCheckable(True)
        self.actionWAP_Anime.setObjectName(_fromUtf8("actionWAP_Anime"))
        self.actionPlay = QtGui.QAction(MainWindow)
        self.actionPlay.setCheckable(True)
        self.actionPlay.setObjectName(_fromUtf8("actionPlay"))
        self.actionPause = QtGui.QAction(MainWindow)
        self.actionPause.setObjectName(_fromUtf8("actionPause"))
        self.actionStop = QtGui.QAction(MainWindow)
        self.actionStop.setObjectName(_fromUtf8("actionStop"))
        self.actionDownload = QtGui.QAction(MainWindow)
        self.actionDownload.setObjectName(_fromUtf8("actionDownload"))
        self.actionDownload_All = QtGui.QAction(MainWindow)
        self.actionDownload_All.setObjectName(_fromUtf8("actionDownload_All"))
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuPlaylist.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())
        self.playlist_toolBar.addAction(self.actionDownload)
        self.playlist_toolBar.addSeparator()
        self.playlist_toolBar.addAction(self.actionDownload_All)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.pushButton_media_play, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.play_clicked)
        QtCore.QObject.connect(self.pushButton_media_pause, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.pause_clicked)
        QtCore.QObject.connect(self.pushButton_media_stop, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.stop_clicked)
        QtCore.QObject.connect(self.actionDownload, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.playlist_download_clicked)
        QtCore.QObject.connect(self.actionDownload_All, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.playlist_download_all_clicked)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.pushButton_media_play, self.pushButton_media_pause)
        MainWindow.setTabOrder(self.pushButton_media_pause, self.pushButton_media_stop)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        item = self.table_vip_standard.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Track", None))
        item = self.table_vip_standard.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Duration", None))
        item = self.table_vip_standard.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Filesize", None))
        item = self.table_vip_standard.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Download Status", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_vip_standard), _translate("MainWindow", "VIP Standard", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_vip_mellow), _translate("MainWindow", "VIP Mellow", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_vip_source), _translate("MainWindow", "VIP Source", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_vip_exiled), _translate("MainWindow", "VIP Exiled", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_wap_anime), _translate("MainWindow", "WAP Anime", None))
        self.pushButton_media_play.setText(_translate("MainWindow", "Play", None))
        self.pushButton_media_pause.setText(_translate("MainWindow", "Pause", None))
        self.pushButton_media_stop.setText(_translate("MainWindow", "Stop", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuPlaylist.setTitle(_translate("MainWindow", "Playlist", None))
        self.menuAbout.setTitle(_translate("MainWindow", "About", None))
        self.playlist_toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.actionVIP_Standard.setText(_translate("MainWindow", "VIP Standard", None))
        self.actionVIP_Standard.setToolTip(_translate("MainWindow", "VIP Standard", None))
        self.actionVIP_Mellow.setText(_translate("MainWindow", "VIP Mellow", None))
        self.actionVIP_Source.setText(_translate("MainWindow", "VIP Source", None))
        self.actionVIP_Exiled.setText(_translate("MainWindow", "VIP Exiled", None))
        self.actionWAP_Anime.setText(_translate("MainWindow", "WAP Anime", None))
        self.actionPlay.setText(_translate("MainWindow", "Play", None))
        self.actionPause.setText(_translate("MainWindow", "Pause", None))
        self.actionStop.setText(_translate("MainWindow", "Stop", None))
        self.actionDownload.setText(_translate("MainWindow", "Download", None))
        self.actionDownload_All.setText(_translate("MainWindow", "Download All from Playlist", None))

from PyQt4 import phonon

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

